### ISSUE TITLE
How to run test documentation

### ISSUE THREAD

**Issue by 3zcurdia** [chaitanyav/fibonacci#1]
First of all let me tell you that I found your gem asome, It teach me a lot of how to make a gem whit a c-extension, but still concern me how to run the test whit the extencion, so I will be tankful if you document that in the readme file

Have a nice Day!

**Comment by chaitanyav** [comment]
Hello,
Thanks for the message, You run test the extension in multiple ways, you can use assertions in the C code itself (e.g. http://www.cplusplus.com/reference/cassert/assert/). Another way is to have a shell script that can build the gem, uninstall existing version of the gem (if exists), install the gem from local and then run the tests using rake.
